library/junos_install_config

Merge in changes from @cvicente to add check mode and writing diffs to a file for junos_install_config.
Added exception information for Config load and Commit check.

junos_install_config: Check mode, file diff, exception handling.

---

library/junos_get_facts
library/junos_install_config
library/junos_install_os
library/junos_zeroize

Add logging for netconify 1.0

---

library/junos_install_config

This adds commit confirm to junos_install_config
Slightly different than community based pull requests
Resolves #57 
Resolves #67

Add commit confirm to install_config

---

library/junos_commit

This adds a new module to perform commits only.

Add junos_commit module

---

README.md
library/junos_srx_cluster

junos_srx_cluster module

---

library/junos_get_facts

Extend junos_get_facts savedir to netconf mode

---

library/junos_rollback

Add the junos_rollback module.
This module will rollback the configuration.  Supports check mode and commit confirm.
Resolves #2

Add junos_rollback

---

README.md

Adding Juniper Networks contact email id.

Updating contact details in README.md

---

library/junos_rpc

My playbook for the same
```yaml
---
- name: Junos OS version
hosts: all
connection: local
gather_facts: no
tasks:
- name: Get rpc run
junos_rpc:
host={{ inventory_hostname }}
user=xxxx
passwd=xxx
rpc=get-interface-information
kwargs="interface_name=em0"
format=text
dest=get_interface_information.conf
register: junos
- name: version
debug: msg="{{ junos.rpc_reply }}"
```

To call any junos rpc.

---

version.py

As there are new addition to module, hence changing minor version number

version number changed to 1.3.0

---

library/junos_rpc

added example for json format for junos >=14.2

junos_rpc examples updated

---

library/junos_get_table.py

Adding junos_get_table to leverage Tables/Views in Ansible.  
Background: https://github.com/networktocode/junos-ansible/issues/1

commit for junos_get_table

---

library/junos_get_table.py

fix for nested tables

---

library/junos_cli
library/junos_rpc

@vnitinv / @stacywsmith 
I used the same code as in junos_ping and junos_rollback etc ..
it should be straight forward but just in case, please can you take a look before merge ? 
Thanks
Damien

Add Timeout option for junos_cli and junos_rpc (#122)

---

library/junos_install_config

Fix for comment 
https://github.com/Juniper/ansible-junos-stdlib/commit/b5d8877813344567424480d4052eefa4764108cf#commitcomment-19029681

junos_install_config: moved imports to proper location in

---

library/junos_jsnapy

snap_pre was broken & snapcheck was expecting testfiles full path

---

library/junos_jsnapy

previous solution was not working
added more checks

Redesign how test files list is constructed, 

---

library/junos_ping
tests/pb.junos_ping.yaml

Add do_not_fragment to junos_ping

---

README.md

update examples to use /project rather than /playbooks

---

Dockerfile

In order to be able to install keys to connect using "ssh-add ˜/.ssh/key"
Added   apk add openssh-client &&\

Include openssh-client library

---

module_utils/juniper_junos_common.py

See a description of the problem being addressed [here](https://github.com/Juniper/ansible-junos-stdlib/issues/326#issuecomment-358417648).

Translate | in output filenames to _. See #326

---

Dockerfile

Made changes required to install pip in juniper/pyez-ansible container.
- apk update to avoid pip installation errors.
- Install pip from py-pip

Dockerfile update to include pip

---

module_utils/juniper_junos_common.py

To support ansible defined variables
Fix #391

added support for ansible_port and ansible_host

---

library/juniper_junos_ping.py
library/juniper_junos_pmtud.py
library/juniper_junos_table.py

Updated sample playbook. Address #389.

---

.dockerignore
.gitignore
Dockerfile
README.md
module_utils/juniper_junos_common.py
requirements.txt

Refactored Dockerfile and cleaned up README

Refactored Dockerfile and cleaned up README

---

module_utils/juniper_junos_common.py
tests/pb.juniper_junos_config.yml
tests/pb.juniper_junos_facts.yml
tests/pb.juniper_junos_jsnapy.yml
tests/pb.juniper_junos_ping.yml
tests/pb.juniper_junos_pmtud.yml
tests/pb.juniper_junos_rpc.yml

I have added the test in Jenkins as well.
Thanks to the tests. I was able to find some minor bugs in `juniper_junos_common` 
- In case we are not able to convert it to bool, we should return `None`. Currently, it causes a `TypeError`.
- The mode should be `ab` instead of `a` to allow python3 to write bytestrings

Added tests for juniper_junos_rpc

---

module_utils/juniper_junos_common.py

We now have seperate branches for ansible-collection(master) and ansible-roles(roles). 
Adding the commit done in the master branch to roles branch.

Merge changes done in collection branch to roles branch also

---

library/juniper_junos_config.py
module_utils/juniper_junos_common.py

Adding functionality to support load_patch. 
Fix for issue #489

Add load patch functionality in ansible roles

---

version.py

Update the git repository version with dev

---

tests/pb.juniper_junos_config.yml
tests/pb.juniper_junos_facts.yml
tests/pb.juniper_junos_ping.yml
tests/pb.juniper_junos_pmtud.yml

testcases added for collection functional testing.

Adding testcases

---

library/juniper_junos_software.py
library/juniper_junos_system.py
module_utils/juniper_junos_common.py

This is for roles branch. A previous pull request is raised for similar changes for collection(master) branch
Changes done to call PyEz functions to handle reboot, shutdown and similar functionalities in junos-ansible.

changes for ansible system actions for roles to be handled in PyEz

---

README.md
ansible_collections/Juniper/junos_collection/plugins/callback/jsnapy.py
ansible_collections/Juniper/junos_collection/plugins/module_utils/juniper_junos_common.py
ansible_collections/Juniper/junos_collection/plugins/modules/juniper_junos_command.py
ansible_collections/Juniper/junos_collection/plugins/modules/juniper_junos_config.py
ansible_collections/Juniper/junos_collection/plugins/modules/juniper_junos_rpc.py
ansible_collections/Juniper/junos_collection/plugins/modules/juniper_junos_software.py
ansible_collections/Juniper/junos_collection/plugins/modules/juniper_junos_system.py
requirements.txt

Changes done to call PyEz functions to handle reboot, shutdown and similar functionalities in junos-ansible being merged from roles to collection.

functionalities in junos-ansible being merged from roles to collection.

---

library/juniper_junos_system.py
module_utils/juniper_junos_common.py

Reboot check modified for the vmhost argument

---

library/juniper_junos_table.py

Code fix went to master branch and missed during transition of collection to be merged in roles branch.

Merge code to roles branch

---

ansible_collections/juniper/device/docs/ansible2rst.py
ansible_collections/juniper/device/docs/command.rst
ansible_collections/juniper/device/docs/config.rst
ansible_collections/juniper/device/docs/facts.rst
ansible_collections/juniper/device/docs/jsnapy.rst
ansible_collections/juniper/device/docs/ping.rst
ansible_collections/juniper/device/docs/pmtud.rst
ansible_collections/juniper/device/docs/rpc.rst
ansible_collections/juniper/device/docs/software.rst
ansible_collections/juniper/device/docs/srx_cluster.rst
ansible_collections/juniper/device/docs/system.rst
ansible_collections/juniper/device/docs/table.rst
ansible_collections/juniper/device/plugins/action/extract_data.py
ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
requirements.txt

Provider is not supported in collections and will be removed.

Removing provider from the readthedocs for collection

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py

During commit configuration, timeout option is missed in ansible. Added timeout option.

fix timeout

---

ansible_collections/juniper/device/version.py
version.py

Ansible v1.0.2 release update

---

ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/modules/software.py
ansible_collections/juniper/device/plugins/modules/system.py

Support for software installation on specific members "member_id" of EX-VC

Fix for issue #613

---

ansible_collections/juniper/device/docs/conf.py

Fix for sphinx build failure with sphinx 7.2.6

Fix for issue #630

---

tests/pb.juniper_junos_rpc.yml

Updated ansible rpc test case playbook

Updated ansible rpc testcase playbook

---

ansible_collections/juniper/device/plugins/connection/pyez.py

Issue:
Normalize value not passed correctly in PyEZ connection rpc.ping() API

Fixed functional testcases for ping and pmutd playbook

---

ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/modules/jsnapy.py
tests/pb.juniper_junos_jsnapy.yml

jsnapy.py 
Added code for persistent pyez connection check and called invoke_jsnapy with required arguments 
pyez.py 
updated snapcheck  - removed file_name with pre_file argument

Fix for pb.juniper_junos_jsnapy.yml

---

README.md
tests/README.md

Fixed README file
Updated steps to execute functional test playbooks
Updated reference to URLs

Fix for ReadMe

---

ansible_collections/juniper/device/version.py
version.py

Ansible Collection v1.0.4 release update

Ansible Collection v1.0.4 release update

---

ansible_collections/juniper/device/galaxy.yml

Ansible collection v1.0.4 release update

v1.0.4 release update

---

ansible_collections/juniper/device/docs/.readthedocs.yaml

Fix for readthedoc build failures

Fix for readthedoc build failures

---

ansible_collections/juniper/device/docs/.readthedocs.yaml

Doc build fix3

---

README.md
ansible_collections/juniper/device/plugins/action/file_copy.py
ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/file_copy.py
tests/pb.juniper_junos_file.yml

Introduced a new module, file_copy, to enable the upload and download of files to and from Junos devices.

Introduced a new module file_copy

---

README.md
ansible_collections/juniper/device/docs/file_copy.rst
ansible_collections/juniper/device/galaxy.yml
ansible_collections/juniper/device/plugins/modules/file_copy.py
ansible_collections/juniper/device/version.py
version.py

Ansible Collection v1.0.5 Release update

Ansible Collection v1.0.5 Release update

---

tests/junos_jsnapy/test_snmp.yml
tests/pb.juniper_junos_jsnapy.yml

Updated  jsnapy module test for dest_dir.

tests for jsnapy dest_dir support

---

ansible_collections/juniper/device/version.py
version.py

[Release v1.0.6 Ansible Collections]
Enhancements done
Introduced dest_dir parameter to save the failed tests https://github.com/Juniper/ansible-junos-stdlib/pull/678
Bugs Fixed
Fixed handling of ping failures when traffic-loss values are of type float https://github.com/Juniper/ansible-junos-stdlib/issues/672
Fixed SyntaxWarning: invalid escape sequence '*' emitted during ansible-playbook execution https://github.com/Juniper/ansible-junos-stdlib/issues/674
Fixed RPC exception handling when RPC is not supported on the platform while using persistent connection https://github.com/Juniper/ansible-junos-stdlib/pull/677

Release v1.0.6 update

---

ansible_collections/juniper/device/plugins/modules/jsnapy.py

results is changed results_loc

Fixed typo results changed results_loc

---

ansible_collections/juniper/device/galaxy.yml
ansible_collections/juniper/device/version.py
requirements.txt

 ansible v1.0.7 release update

---

tests/pb.juniper_junos_config.yml
version.py

release v1.0.7 update

---

ansible_collections/juniper/device/plugins/modules/software.py

Fix for issue #709 ,  to support vmhost upgrade with partitions with version check.
Updated the code to use the show vmhost version details to check the image version

Fix for issue #709

---

ansible_collections/juniper/device/plugins/modules/rpc.py
ansible_collections/juniper/device/tests/integration/targets/junos_rpc/tests/common/rpc.yml
tests/pb.juniper_junos_rpc.yml

Fix to handle if response of RPC is JSON format of type <class 'dict'>

Fix for issue #730

---

ansible_collections/juniper/device/tests/integration/targets/junos_file/tasks/main.yml
ansible_collections/juniper/device/tests/integration/targets/junos_file/tests/common/file.yml
ansible_collections/juniper/device/tests/unit/test_file_copy.py

file_copy module related Unit and Integrations test by @dineshbaburam91

unit and integration test updates

---

ansible_collections/juniper/device/CHANGELOG.rst
ansible_collections/juniper/device/galaxy.yml
ansible_collections/juniper/device/version.py
version.py

ansible release update

---

ansible_collections/juniper/device/version.py

Ansible collection dev version update

dev version update
