Juniper/ansible-junos-stdlib

library/junos_get_facts
library/junos_install_config
library/junos_install_os
library/junos_shutdown
library/junos_zeroize

Bump up required PyEZ version to 1.2.1
Switch from re to LooseVersion to test version (way cooler)
Resolves #64

Bump req. pyez version to 1.2.1

---

library/junos_install_config

Supported on Junos_PyEZ, this allows configuration files with the "replace:" statement to be pushed and correctly interpreted (similar to a "load replace" on Juniper CLIs.
Please let me know if I need to change anything.

Adds support for the "replace:" statement

---

library/junos_install_config

This update moves the NETCONF stuff into a single function.
Proper exception handling has been included as well as a commit_check prior to actual commit.
*Note* This will prevent configurations with warnings from committing.  This is the default behavior of PyEZ <=1.2.  Future versions of PyEZ will support multiple rpc-error elements and as such a new exception class will be created to handle warnings only.
```
TASK: [Install config] ********************************************************
failed: [pabst.englab.juniper.net] => {"failed": true}
msg: Unable to commit configuration: CommitError(edit_path: [edit security policies from-zone corp to-zone], bad_element: corp, message: mgd: Security zone must be defined)
FATAL: all hosts have already failed -- aborting
PLAY RECAP …
```

Refactor junos_install_config netconf into single funtion

---

library/junos_get_config

This adds the ability to retrieve the configuration of a device and save it to a file.
get_config options and filters are supported.
```yaml
---
- name: Get Device Config
hosts: all
connection: local
gather_facts: no
tasks:
- name: Get configuration
junos_get_config:
host: "{{ inventory_hostname }}"
user:
passwd:
logfile: get_config.log
dest: "{{ inventory_hostname }}.xml"
format: xml
filter: "interfaces"
options: {inherit: inherit, groups: groups}
register: junos
```
```
2015-07-30 15:32:55,952:CONFIG:pabst.englab.juniper.net:connecting to host: user@pabst.englab.juniper.net:830
2015-07-30 15:33:02,036:CONFIG:pabst.englab.juniper.net:Getting config with filter=<configuration><interfaces/></configuration>
2015-07-30 15:33:02,036:CONFIG:pabst.englab.juniper.net:Getting config with …
```

Add junos_get_config

---

library/junos_commit

Add a timeout argument to the junos_commit module to support confirming a commit on a device which is slow and/or has a large config.

Add a timeout argument to the junos_commit module

---

library/junos_get_facts

Ansible 2 adds a feature to search the modules return value for any
strings which should not be logged. This feature only handles built-in
data types and does not handle custom objects.
The junos_get_facts module was returning a junos.version_info object
which caused this new feature to raise a TypeError.
Since all Ansible return values are passed via JSON, the junos.version_info
object was previously getting converted to a dictionary anyway, so this
change should be backwards compatible with Ansible 1 as well.

Addressing issue #102.

---

library/junos_cli

Hi
I created a new role to simply execute a show /request cli command on a device and save the result locally
As discussed, it will be great to convert XML to JSON properly and feed JSON natively into Ansible, this part is not available today 
Thanks
Damien

Add role junos_cli to execute CLI on device and save output locally

---

library/junos_get_config

The filter argument string was improperly converted into XML.
Rather than building an XML hierarchy of elements, a list of elements
was created. This fix creates an XML hierarchy.

Address Issue #120

---

library/junos_jsnapy

with given changes yml file can take test files directly
```yml
---
- hosts: all
roles:
- Juniper.junos
connection: local
gather_facts: no
tasks:
- name: JUNOS Post Checklist
junos_jsnapy:
host={{ inventory_hostname }}
user=‘xxxx'
passwd=‘xxxx'
action='snapcheck'
test_files=test_exists.yml,test_is_equal.yml
register: jsnapy
- name: Debug jsnapy
debug: msg="{{jsnapy}}"
```

added test_files option

---

library/junos_cli
library/junos_rpc

there was a typo in junos_cli, module arguments in that file are in 'args' but the code for timeout was copy/pasted form junos_rpc where they are in 'm_args'
The rest is just some cleanup around handling the default value and casting types.

Fix typo in timeout in junos_cli, simplified default timeout handling

---

library/junos_rpc

I need the regex to match all the following:
```
kwargs=vme
kwargs=xe-0/0/0
kwargs=fpx0
kwargs=me0.0
```
Current state don't match xe/ge/et itnerfaces due to forward slash not in the regex expression.

fix regex to match xe/ge/et interfaces

---

library/junos_install_config

Mixed tabs and whitespaces breaks script.

fix mixed tabs and whitespaces

---

library/junos_cli
library/junos_commit
library/junos_get_config
library/junos_get_facts
library/junos_get_table
library/junos_install_config
library/junos_install_os
library/junos_jsnapy
library/junos_ping
library/junos_rollback
library/junos_rpc
library/junos_shutdown
library/junos_srx_cluster
library/junos_zeroize

Now if ImportError is due to different package, error will give proper message
```
$ ansible-playbook facts_gather.yml 
PLAY ***************************************************************************
TASK [gather facts] ************************************************************
fatal: [10.221.150.172]: FAILED! => {"changed": false, "failed": true, "msg": "ImportError: No module named lxml"}
```

ImportError proper message

---

library/junos_cli
library/junos_commit
library/junos_get_config
library/junos_get_facts
library/junos_get_table
library/junos_install_config
library/junos_install_os
library/junos_jsnapy
library/junos_ping
library/junos_rollback
library/junos_rpc
library/junos_shutdown
library/junos_srx_cluster
library/junos_zeroize

example:
To take mode and port. 
```yaml
- name: Checking NETCONF connectivity
wait_for: host={{ inventory_hostname }} timeout=5
- name: Get configs
junos_get_config:
user: "{{ USERNAME }}"
passwd: "{{ PASSWORD }}"
port: 7011
mode: "telnet"
logfile: get_config.log
format: xml
```

Functionalities to work on console connection using PyEZ 2.0

---

setup.py

We get this error last week on our Rhel7 server.

Fix missing interpreter: (on Rhel7)

---

library/junos_cli
library/junos_commit
library/junos_get_config
library/junos_get_facts
library/junos_get_table
library/junos_install_config
library/junos_install_os
library/junos_jsnapy
library/junos_ping
library/junos_rollback
library/junos_rpc
library/junos_shutdown
library/junos_srx_cluster
library/junos_zeroize

Currently a run will show the password as plaintext, this minor change prevents logging such a sensitive variable. For example:
`fatal: [router01]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"check_commit_wait": null, "comment": null, "confirm": null, "console": null, "diffs_file": null, "file": "output/router01/compiled.set", "host": "192.0.2.40", "logfile": null, "mode": null, "overwrite": false, "passwd": "myUbers3ck3tpass!#@", "port": "830" ...`
With this change
`fatal: [router01]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"check_commit_wait": null, "comment": null, "confirm": null, "console": null, "diffs_file": null, "file": "output/router01/compiled.set", "host": "192.0.2.40", "logfile": null, "mode": null, …

Don't log password to stdout

---

library/junos_cli

junos_cli / Add test before writing output to dest

---

library/junos_rpc

```yaml
tasks:
- name: Get interface information
junos_rpc:
host: "{{ inventory_hostname }}"
rpc: get-interface-information
kwargs:
interface_name: em0
media: True
```

To support kwargs as dict into junos_rpc

---

library/junos_jsnapy

- Remove dest option from doc, 
- Indicate `action` as mandatory in doc,
- Add examples for snap_pre & snap_post

[junos_jsnapy] Clean up the inline documentation

---

.travis.yml
library/junos_cli
tests/.travis_ansible_python.yaml
tests/ansible.cfg

I made a silly mistake with #193 :(
Hopefully we'll catch that with proper unit test moving forward

junos_cli - Fix for > global name 'dest' is not defined

---

library/junos_cli
library/junos_commit
library/junos_get_config
library/junos_get_facts
library/junos_get_table
library/junos_install_config
library/junos_install_os
library/junos_jsnapy
library/junos_ping
library/junos_rollback
library/junos_rpc
library/junos_shutdown
library/junos_srx_cluster
library/junos_zeroize

Now we can do something like
```yaml
- name: gather facts
junos_get_facts:
host={{ inventory_hostname }}
user='xxxx'
passwd='Test123'
ssh_private_key_file='/Users/nitinkr/.ssh/id_rsa_vmx'
register: junos
- name: Verify JUNOS version
debug: msg="{{junos.facts.version}}"
```
Here I am passing password (passphrase) for my ssh private key file.

Priv ssh key

---

library/junos_get_facts

Ansible 2 doesn't like custom objects in a module's return value, and
after Juniper/py-junos-eznc#638 PyEZ facts are now a custom object rather than a true
dict. Since facts are read-only, we must begin by copying facts into a dict.
Also, since PyEZ facts are now "on-demand", this must be done before closing
the connection. These changes remain backwards compatible with older PyEZ
versions that have older fact gathering code.

Modify junos_get_facts to be compatible with Juniper/py-junos-eznc#638.

---

library/junos_get_config

With Ansible version >=2.1, if the type is not defined, the value is assigned as string only.
Hence change to take explicitly define type of options param
refer: https://github.com/ansible/ansible/issues/19589

junos_get_config options type defined for Ansible >=2.1

---

library/junos_cli
library/junos_commit
library/junos_get_config
library/junos_get_facts
library/junos_install_config
library/junos_install_os
library/junos_jsnapy
library/junos_ping
library/junos_rollback
library/junos_rpc
library/junos_shutdown
library/junos_srx_cluster
library/junos_zeroize

Ansible 2.3 attempts to import modules to see if `USE_PERSISTENT_CONNECTION` is set. The modules are incorrectly executed upon import because they lack a `if __name__ == '__main__':` conditional.
This is an alternate way to address ansible/ansible#22590. I suggest that ansible/ansible#22590 should still be merged to avoid the problem for users which are running a version of these modules which don't yet have this fix.

Allow modules to import cleanly

---

library/junos_get_facts

After Juniper/py-junos-eznc#638, PyEZ facts are now a custom object
rather than a true dict. In addition, facts are now read-only.
This was partially addressed in #210, but I missed the case
where the `savedir` option is specified to dump the facts into
JSON files. The same fix is also required in this case.

JSON dump of Junos facts requires native Python data types.

---

library/junos_install_os

junos_install_os used to fail without 'logfile' parameter

---

library/junos_install_config

user can now pass ignore_warning as per https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/config.py#L336
```yaml
tasks:
- name: install config to device
junos_install_config:
host: "{{ inventory_hostname }}"
ignore_warning: True
file: xxxx.set
```
```yaml
tasks:
- name: install config to device
junos_install_config:
host: "{{ inventory_hostname }}"
ignore_warning: "statement not found"
file: xxxx.set
```
```yaml
tasks:
- name: install config to device
junos_install_config:
host: "{{ inventory_hostname }}"
ignore_warning:
- "statement not found"
- "testing"
file: xxxx.set
```

ignore_warning support for junos_install_config

---

README.md

Add text for ansible-galaxy installation from GitHub

---

README.md
library/junos_pmtud
tests/pb.junos_pmtud.yaml

Add junos_pmtud module to perform path MTU discovery on Junos devices. 
Finds path MTU to destination IP, with defaults it finds MTU in range 989-1500 B in exactly 9 steps (always log2(max_range) steps). Tolerates any packet loss lower than 100 pct.

add junos_pmtud module

---

library/junos_install_config

Using the latter, one can compare the generated configuration changes against the running configuration. Changes are not staged to the equipment. Similar to "show | compare" in Juniper edit mode.

"compare" mode is added. 

---

library/junos_commit

This is useful when doing first a "commit confirm" followed directly by a "commit check".
That way, if the commit breaks connectivity to the device, the configuration rollbacks, if there is still connectivity the commit check is faster than a full commit and doesn't trigger configuration archival, etc..
Example:
``` yaml
- name: "Do a commit confirmed 2 or commit check"
junos_install_config:
host={{ inventory_hostname }}
port=22
file="{{ assembled_conf }}"
overwrite=false
replace=true
diffs_file="{{ logs_dir }}/{{ inventory_hostname }}.diff"
logfile="{{ logs_dir }}/{{ inventory_hostname }}.log"
timeout="300"
comment="Ansible"
confirm="2"
register: push_result
- name: "commit check to confirm the previous commit"
junos_commit:
host={{ inventory_hostname }}
check=true
when: not check_mode …
```

Add a parameter to only do a commit check

---

library/juniper_junos_config.py
version.py

When `retrieve` is set and `load` and `rollback` are not set, then
`check`, `diff`, and `commit` should all default to `False`.
This allows just a simple config retrieval similar to the old `junos_get_config` without having to specify a lot of extra parameters.

Better defaults for juniper_junos_config.

---

Dockerfile
library/juniper_junos_command.py
library/juniper_junos_config.py
library/juniper_junos_facts.py
library/juniper_junos_jsnapy.py
library/juniper_junos_rpc.py
library/juniper_junos_table.py
module_utils/juniper_junos_common.py
requirements.txt

- Also bump required JSNAPy version to the new 1.2.1.
- Update/correct some documentation in the common module.
- Reorganize order of methods in the common module.

Only require libraries if they are actually needed by a module. Fixes #301.

---

module_utils/juniper_junos_common.py

* Add back support of serial console connections with `console` option.
* Support serial console connections with `mode='serial'` option.
* Cleanly handle if JSNAPy 1.2.0 is installed
* Default the `port` option appropriately based on the value of the `mode` option.

Serial console support

---

library/juniper_junos_system.py
version.py

The `in_min` and `at` arguments to `juniper_junos_system` were not handled
correctly. The generated RPC argument looked like `<in text="5"/>`, when it
should have been `<in>5</in>`.

Correctly handle in_min and at arguments to juniper_junos_system. Fixes #310.

---

action_plugins/_junos_install_config.py

There was a backwards compatibility issue with `junos_install_config`.
```
junos_install_config:
check_commit: false
```
In 1.4.3, the above used to perform a diff, but not perform a "commit check"
or a "commit". Now, it performs the diff, but it also does a "commit".
This change restores the 1.4.3 behavior where:
```
junos_install_config:
check_commit: false
```
will only perform the diff and not perform a "commit".

Mimic old behavior for junos_install_config with check_commit = False.

---

library/juniper_junos_ping.py

The `acceptable_percent_loss` parameter to `juniper_junos_ping` was not being correctly interpreted. This led to the module incorrectly returning a pass even when it should have failed because the `acceptable_percent_loss` was exceeded.

Fix acceptable_percent_loss parameter to juniper_junos_ping.

---

callback_plugins/jsnapy.py
docs/ansible2rst.py
library/juniper_junos_table.py
module_utils/juniper_junos_common.py

iteritems() gives an error in _junos_table as type of variable "data" is not a dictionary, rather it is a PyEZ factory table object which has a custom items() method defined.
Changing back iteritems(data) to data.items()

Correcting wrong usage of iteritems()

---

library/juniper_junos_facts.py

When PyEZ is unable to gather a fact from a Junos device, the key still exists
in the dev.facts attribute, but has a value of None. The checks for converting
the `version_info` and `junos_info` facts from their custom types to a dict
did not properly account for this situation. IN that case, they would attempt
to convert `None` to a `dict` and throw an exception.
This PR more gracefully handles that situation. However, it does not fix the
underlying Junos or PyEZ issue which might lead to being unable to collect
the `version_info` and `junos_info` facts from a device. That would need
to be addresses separately in PyEZ.

Handle empty `version_info` and `junos_info` facts more gracefully. Addresses #360.

---

module_utils/juniper_junos_common.py

juniper_junos_common.py does not support user defined path for SSH configuration, so by default ~/.ssh/config is used by PyEZ. With this trivial patch one can define alternative ssh_config file, for example /etc/ssh/ssh_config that is then further passed to PyEZ.

Add support for defining ssh_config path

---

callback_plugins/jsnapy.py

- From Ansible 2.4, module_name is not passed as part of result to
v2_runner_on_ok(). So, the current code returns a Null object without
adding the hosts.
- Corrected by removing usage of module_name to add hosts in
junos_jsnapy callback plugin.

Fixed junos_jsnapy callback plugin

---

.travis.yml
library/juniper_junos_command.py
library/juniper_junos_config.py
library/juniper_junos_facts.py
library/juniper_junos_jsnapy.py
library/juniper_junos_ping.py
library/juniper_junos_pmtud.py
library/juniper_junos_rpc.py
library/juniper_junos_software.py
library/juniper_junos_srx_cluster.py
library/juniper_junos_system.py
library/juniper_junos_table.py
module_utils/juniper_junos_common.py

From Ansible 2.1, Ansible uses Ansiballz framework for assembling modules,
But custom module_utils directory is supported from Ansible 2.3 .
Please find the reference for the issue [here](https://groups.google.com/forum/#!topic/ansible-project/J8FL7Z1J1Mw)
Ansiballz packages modules_utils under ansible.module_utils, so juniper_junos_common can be imported by using -
`from ansible.module_utils import juniper_junos_common`

Module utils ansiballz integration

---

library/juniper_junos_software.py
library/juniper_junos_system.py

Updated reboot, shutdown and halt rpc calls for WR-Linux HW.

---

README.md
module_utils/juniper_junos_common.py

In newer versions of OpenSSH, keys are generated in the OPENSSH format, but paramiko needs the RSA PEM format. I've added instructions to check for, convert, and create keys in the proper format.

Adding docs to clarify the usage of ssh_private_key_file

---

library/juniper_junos_rpc.py

RPC: `get_config` is treated specially in both PyEZ and juniper_junos_rpc. The current code doesn't pass the format option to PyEZ's `get_config`, which returns an XML response instead of text response, causing the incorrect behavior.
Corrected the behavior by passing down the format option to PyEZ.
Links:
https://github.com/Juniper/py-junos-eznc/blob/472408c3e7a8dd67001c09589c0cf35faad7e829/lib/jnpr/junos/rpcmeta.py#L26-L38

Fixes issue #434

---

requirements.txt

Removed requirements.txt file for security reason

remove requirements.txt file

---

library/juniper_junos_config.py
module_utils/juniper_junos_common.py

Supporting openconfig
```
tasks:
- name: Check open-config configuration
juniper_junos_config:
retrieve: 'committed'
model: "custom"
filter: "l2vpn"
remove_ns: False
namespace: "http://yang.juniper.net/customyang/l2vpn"
format: "xml"
register: response
```
```
TASK [Print result] *****************************************************************************************************************************
ok: [10.204.49.113] => {
"response.config_lines": [
"<l2vpn xmlns=\"http://yang.juniper.net/customyang/l2vpn\">", 
"    <global>", 
"        <as-number>65000</as-number>", 
"        <side>hub</side>", 
"    </global>", 
"</l2vpn>", 
""
]
}
```

Openconfig and yang supports in  juniper_junos_config module

---

library/juniper_junos_config.py
module_utils/juniper_junos_common.py

I noticed that `juniper_junos_common/open_configuration` wasn't respecting the `ignore_warning` parameter.
In our environment we were getting some error when 2 tasks are trying to run a config diff + check at the same time (even in private mode)
```
fatal: [rs1-aw38-c1-ash1 -> localhost]: FAILED! => changed=false
msg: |-
Unable to open the configuration in private mode: RpcError(severity: warning, bad_element: None, message: warning: changes cannot be committed while 'configure exclusive' is active
warning: uncommitted changes will be discarded on exit)
```
Here is the task
```yaml
juniper_junos_config:
retrieve: candidate
load: overwrite
config_mode: private
diff: true
check: true
commit: false
src: "{{ junos_conf }}"
provider: "{{ credential }}"
```
> there might be another issue here …

Add support for ignore_warning in juniper_junos_common/open_configuration

---

library/juniper_junos_config.py

--diff doesn't show the diff as expected.
we changed the handling for the `juniper_junos_config` a bit to return the diff correctly, so that ansible is showing it.
output before the fix:
```
ansible-playbook sitegroups/bgp-router.yml -l XYZ -CD
PLAY [provision bgp-routers] *************************************
TASK [bgp-router : install system configuration] *************************************
changed: [XYZ]
PLAY RECAP *************************************
XYZ            : ok=4    changed=1    unreachable=0    failed=0
```
output after the change:
```
ansible-playbook sitegroups/bgp-router.yml -l XYZ -CD
PLAY [provision bgp-routers] *************************************
TASK [bgp-router : install system configuration] *************************************
[edit system …
```

--diff is not working correctly

---

library/juniper_junos_config.py

Change #427 modified behavior of juniper_junos_config (diff is not
a string anymore - it's a dict now). Behavior is now inconsistent
with the documentation.

juniper_junos_config: update doc

---

Dockerfile

PyEZ base images is build on top of python3. We dont need python2 as its EOL now.

removed python2

---

ansible_collection/Juniper/junos/plugins/module_utils/juniper_junos_common.py

By default, Ansible's `boolean` helper throws an error when given a non-truthy argument. This micro-patch restores the `juniper_junos_config` module's ability to ignore specific warnings passed to the `ignore_warning` parameter in list or string format.

Fix ignore_warning with non-boolean arguments

---

action_plugins/juniper_junos_common_action.py
module_utils/juniper_junos_common.py

Pass `inventory_hostname` to module for building filenames

---

library/juniper_junos_command.py
library/juniper_junos_config.py
module_utils/juniper_junos_common.py

Pass and parse the ignore_warning argument in diff for juniper_junos_config.

Adding ignore warning for diff in juniper junos config

---

callback_plugins/jsnapy.py

Adding whitelist to be added in ansible.cfg for jsnapy callback to be enabled or disabled.
jsnapy callback will no more be enabled by default.

Enabling whitelist feature for jsnapy callback

---

library/juniper_junos_rpc.py

Issue resolved 
Exception handling error for get-config #502 
Moved the rpc variable to have proper exception handling.

rpc variable defined for exception handling for get-config

---

callback_plugins/jsnapy.py

Jsnapy should check for final_result and count values before calling them as a member element as it can be NULL in some scenarios.
Fixes #209

Fix for jsnapy callback when testcase result is NULL

---

README.md
library/juniper_junos_software.py
requirements.txt
version.py

When there is insufficient space left on the device, juniper_junos_software module needs to return a correct error when the upgrade procedure tries to untar the image. 
#495

Correct message  in case of failure during software install

---

module_utils/juniper_junos_common.py

diff() function in the required junos-eznc version (>=2.2.0) no longer has ignore_warning parameter.

Stop passing ignore_warning param to diff()

---

library/juniper_junos_system.py

Modify the default value of in_min to 0.

default value is modified in variable in_min

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/rpc.py

For kwargs in rpc the module checks if the value can be transformed to bool and converts it.
A flag can now be added in the kwargs to not convert into bool and keep the value as string.
The mandatory boolean conversion is not removed to keep backward compatibility.
For ex -
juniper_junos_rpc:
rpc: get-rollback-information
kwargs:
allow_bool_values: "0"
rollback: "2"
compare: 0
it will resolve #538 in collections.

Adding allow_bool for rpc and enhancing log error

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py

Description:
etree import may give an issue if libxml2 is not installed. Modification done in code to have proper import done.

Etree import modification

---

ansible_collections/juniper/device/plugins/modules/table.py

[deprecation notice](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation)
The `load()` function now requires parameter `loader=Loader`, which will be enough to break the ability to load YAML within the `table.py` module.
Since the YAML file contains data types (str, int, lists), we updated the call to use `yaml.safe_load()` instead.
> pb.get.arp.yaml
```yaml
- name: Get ARP information using Junos PyEZ Table
table:        
user: "root"
passwd: "juniper123"
file: "arp.yaml"
path: "{{ playbook_dir }}"
register: result
```
> execution will fail
```bash
`--> ansible-playbook pb.get.arp.yaml
PLAY [all] *****************************************************************************************************************************************************************
TASK [Get …
```

accounting for deprecation of yaml.load() function

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/config.py

Introduced "commit_sync" and "commit_force_sync" under juniper.device.config module
```
- name: "Confirm the commit with a commit check"
juniper.device.config:
check: true
diff: false
comment: "Juniper Network"
commit_force_sync: True
register: response
```
```
- name: "Confirm the commit with a commit check"
juniper.device.config:
check: true
diff: false
comment: "Juniper Network"
commit_sync: True
register: response
```

Introduced commit_sync and commit_force_sync

---

tests/junos_jsnapy/test_junos_storage.yml
tests/pb.juniper_junos_config.yml
tests/pb.juniper_junos_jsnapy.yml
tests/pb.juniper_junos_rpc.yml
tests/pb.juniper_junos_software.yml
tests/pb.juniper_junos_srx_cluster.yml
tests/pb.juniper_junos_system.yml

fixed minor issues with test playbooks

updated test playbooks

---

ansible_collections/juniper/device/plugins/modules/rpc.py
tests/pb.juniper_junos_rpc.yml

Fix for sphinx build failure

---

ansible_collections/juniper/device/docs/jsnapy.rst
ansible_collections/juniper/device/plugins/modules/jsnapy.py

The documentation link in jsnapy.rst and snapy.py points to an outdated link: https://www.juniper.net/uk/en/training/jnbooks/day-one/automation-series/jsnapy/.
Updated it to https://www.juniper.net/documentation/en_US/day-one-books/DO_JSNAPy.zip

fix for issue #612

---

ansible_collections/juniper/device/plugins/action/extract_data.py

It is no longer possible to pass through credentials on the command line using -u, -k or --private-key since ansible-core 2.13. This fix addresses this issue by checking for them within `self._play_context` and populating `connection_args` if they aren't present. This has been tested with `ansible-core>=2.12,<=2.14`.
Caveat - I am not that familiar with the coding standards of Ansible collections so there might be a better way to achieve this, but people are currently unable to authenticate with later versions of ansible-core.

apply fix for issue #592 - pass through auth command line arguments

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py

As per Ansible documentation 
https://github.com/ansible/ansible/blob/6ac0ea35672eed7778f530b5cc7751d41b09c43a/docs/docsite/rst/porting_guides/porting_guide_core_2.11.rst#id27
_check_type_dict() is removed
_check_type_dict() --> [:func:`ansible.module_utils.common.validation.check_type_dict`]
Logs:
```
~/ansible_release_v103/ansible-junos-stdlib/tests# cat pb.juniper_junos_persistent_conn.yml 
---
- name: Test juniper.device.rpc module
hosts: all
connection: juniper.device.pyez
gather_facts: no
collections:
- juniper.device
tasks:
#################
- name: Get Device Configuration for interface
rpc:
rpc: get-config
format: xml
filter: <configuration><groups><name>re0</name></groups></configuration>
attr: name=re0
register: test7
ignore_errors: True
tags: [ test7 ]
- name: Check TEST 7 …
```

Fix for issue #620

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/config.py

1. Supported config mode : private, batch, dynamic, exclusive.
2. By default, config mode is exclusive.
3. Supported config mode : ephemeral (default) and ephemeral (user defined instance).
4. Ephemeral db doesn't support "show | compare" command. So, set diff as False in case of config mode ephemeral.
root@> configure ephemeral
warning: uncommitted changes will be discarded on exit Entering configuration mode
root@# show | compare
^
syntax error, expecting <command>.

Supported configuration mode: private, batch, dynamic, exclusive and ephemeral

---

ansible_collections/juniper/device/plugins/connection/pyez.py
tests/inventory
tests/pb.juniper_junos_command.yml
tests/pb.juniper_junos_config.yml

1. Added inventory template file to run ansible functional test cases for local and PyEZ connection
2. Updated command and config playbook-related test cases.
3. Fixed PyEZ connection rollback configuration issue

Fixed Ansible Functional testcases

---

ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/modules/software.py

Fix for reboot exception handling.

Fix for play pb.juniper_junos_software_member.yml

---

ansible_collections/juniper/device/plugins/modules/software.py
tests/ansible.cfg

Fix for JSON encoder error “TypeError: Object of type function is not JSON serializable”

Fix for Object of type function is not JSON serializable

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py

PyEZ connection commit_configuration API parameter data are mismatched. So it impacts commit RPC when the commit operation is performed.
I updated the valid parameter in commit_configuration API  The output log is below.
```
#################
- name: "Execute set configuration"
config:
load: "set"
format: "set"
lines: 'set system login message "Login"'
comment: "comment"
register: test1
tags: [ test1 ]
```
```
May  8 04:34:23 [NETCONF] - [26690] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:6f6d5aa0-d23a-4e5e-b1cb-2fd2b080b23e"><commit-configuration><log>comment</log></commit-configuration></nc:rpc>]]>]]>
```

Updated commit_configuration API  parameter for PyEZ connection.

---

ansible_collections/juniper/device/plugins/modules/software.py

For Persistent PyEZ connection , during installation of re1 , Exception ansible.module_utils.connection.ConnectionError is raised,  added code to handle if the exception is ConnectionError , else we will raise any other exceptions .

handling ansible.module_utils.connection.ConnectionError

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py

For persistent PyEZ connection , if we specify path of the config file as relative path , it fails with following error 
'data': \"Failure loading the configuraton: [Errno 2] No such file or directory: 'junos.conf'
So, added code to convert the path to absolute path of src file .

Fix for issue #580

---

ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/config.py
tests/pb.juniper_junos_config.yml

added timeout parameter and passed it to commit_configuration
example:
- name: "Load configuration from a local file and commit"
juniper.device.config:
load: "merge"
src: "junos_jsnapy/junos.conf"
confirmed: 20
timeout: 120

Fix for the issue #607

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/software.py

Fixed SyntaxWarning: invalid escape sequence emitted on Python 3.12 version.

Fix for issue #674 syntax warnings

---

ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py

for ping command response,  packet loss values might of type float values, so added the code to read the value in float and round  of it to nearest  integer value before comparing it with acceptable_packet_loss.

fix for issue #672 to handle float values

---

ansible_collections/juniper/device/plugins/modules/rpc.py

When performing an RPC get with an RPC that is not implemented for a platform, it fails when using a PyEZ connection. With a local connection, the response is “Unable to execute the RPC” and it continues with the next RPC get. PyEZ behavior should be the same as with the local connection.

Fixed rpd module related issue

---

ansible_collections/juniper/device/plugins/modules/jsnapy.py

Added to support to save the failed  test result files to a user specified directory - dest_dir: "{{ backup_dir }}"
with filename format for issue #676
```
<hostname>_<test_name>.text
Ex:
- name: "Check after PRE - POST check"
juniper.device.jsnapy:
dir: "{{ JSNAPy_dir }}"
test_files:
- system_util_baseline.yml
- verify_ospf_neighbor.yml
- test_chassis_alarms.yml
logfile: "{{tlogfile}}"
action: "snapcheck"
dest_dir: "{{ backup_dir }}"
register: test_check
tags:
- jsnapy
test file: system_util_baseline.yml
test details:
cat jsnapy_TEST_FILES/system_util_baseline.yml 
tests_include:
- check_core_dumps
- check_system_memory_usage
#- check_system_resource_usage
check_core_dumps:
- command: show system core-dumps
- iterate:
xpath: multi-routing-engine-item
id: re-name
tests:
- no-diff: …
```

support to save the failed tests to dest_dir for local and pyez connection

---

ansible_collections/juniper/device/docs/ansible2rst.py

Fix for import error
from collections import MutableSet, MutableSequence
ImportError: cannot import name 'MutableSet' from 'collections'

Fix for import error

---

ansible_collections/juniper/device/plugins/modules/pmtud.py

when ping packet loss value is in float then module fails with following error
ValueError: invalid literal for int() with base 10: '33.3333'
Added code to read the value as float and round of the value to nearest integer.

fix for ping packet loss in float

---

ansible_collections/juniper/device/galaxy.yml

Just fixing the link!
Why? 
* It was accidentally pointing to [readthedocs site for the "Juniper.junos Ansible Modules"](https://junos-ansible-modules.readthedocs.io/en/2.4.0/)
* It should instead point to [readthedocs site for the "juniper.device Ansible Modules"](https://ansible-juniper-collection.readthedocs.io)
Importantly, I hope this change will fix the "Docs site" hyperlink at [the galaxy.ansible.com page for this Ansible Collection](https://galaxy.ansible.com/ui/repo/published/juniper/device/docs/), seen in screenshot below:

Fix galaxy.yml "documentation" link

---

ansible_collections/juniper/device/plugins/modules/software.py

Fix version extraction from filename for ex2300 firmware (fixes #694)

---

ansible_collections/juniper/device/docs/ansible2rst.py
ansible_collections/juniper/device/docs/conf.py
ansible_collections/juniper/device/plugins/action/file_copy.py
ansible_collections/juniper/device/plugins/action/juniper_junos_common_action.py
ansible_collections/juniper/device/plugins/callback/jsnapy.py
ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/module_utils/configuration.py
ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/command.py
ansible_collections/juniper/device/plugins/modules/config.py
ansible_collections/juniper/device/plugins/modules/facts.py
ansible_collections/juniper/device/plugins/modules/file_copy.py
ansible_collections/juniper/device/plugins/modules/jsnapy.py
ansible_collections/juniper/device/plugins/modules/ping.py
ansible_collections/juniper/device/plugins/modules/pmtud.py
ansible_collections/juniper/device/plugins/modules/rpc.py
ansible_collections/juniper/device/plugins/modules/software.py
ansible_collections/juniper/device/plugins/modules/srx_cluster.py
ansible_collections/juniper/device/plugins/modules/system.py
ansible_collections/juniper/device/plugins/modules/table.py
ansible_collections/juniper/device/version.py

Fixed Sanity test issues

---

ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/command.py

Fix to handle JSON command and config response.

Fix for JSON response handle

---

DOCKER-EXAMPLES.md
Dockerfile
README.md
entrypoint.sh

Ansible Dockerfile update #706 706

Dockerfile update

---

ansible_collections/juniper/device/plugins/connection/pyez.py
ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py
ansible_collections/juniper/device/plugins/modules/file_copy.py
tests/pb.juniper_junos_file.yml

1. A new option, "protocol," has been added to allow users to choose the file transfer method: SCP or FTP. This is an optional parameter, with SCP set as the default.
2. A new option, "checksum," has been introduced to enable or disable validation using a boolean value of True or False. This is also an optional parameter, with True set as the default. When enabled, it validates the MD5 checksum algorithm before and after the file transfer. If set to False, no validation will be performed.
3. A new optional parameter, "transfer-file," allows you to specify the name of the file to be transferred. For example, if you want to copy a file named "XYZ" to a remote destination with a different name, "ABC," you can specify "ABC" in the transfer-file parameter. By default, the parameter will use …

Enhanced file_copy module

---

README.md
ansible_collections/juniper/device/README.md
ansible_collections/juniper/device/plugins/callback/jsnapy.py

Fix for Ansible Automation hub upload review comments
```
Item #1 Error in import logs:
callback juniper.device.jsnapy missing documentation (or could not parse documentation): No documentation available for juniper.device.jsnapy (/tmp/tmpsxl64wuk/ansible_collections/juniper/device/plugins/callback/jsnapy.py)
Item #2 Support statement in the README
Item #3 Address requested changes to README from version 1.0.8. 
```
```
(ansiahrev1) root@masterhost:~/ansible_autohub_review1/ansible-junos-stdlib/ansible_collections/juniper/device# python -m galaxy_importer.main juniper-device-1.0.9.tar.gz 
Importing with galaxy-importer 0.4.33
Getting doc strings via ansible-doc
Finding content inside collection
Loading action command
Loading action config
Loading action extract_data
Loading action facts …
```

Fix Ansible automation hub support review comments
